import type { Account, Agency, LinkageError, Contract, Invoice, Payment, RouteIntegration, Notification, OpsLog, Plan, Agent, AgentContract, AgentMonthlyPerformance, AgentMonthlyEntitlement, AgentSettlement } from '@/domain/types'

const ORG_ID = 'org-001'
const USER_ID = 'user-001'

const now = new Date()
const thisMonth = new Date(now.getFullYear(), now.getMonth(), 1)
const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1)
const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1)

export const plans: Plan[] = [
  {
    id: 'plan-001',
    orgId: ORG_ID,
    name: 'スタンダードプラン',
    monthlyPrice: 30000,
    setupFee: 50000,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'plan-002',
    orgId: ORG_ID,
    name: 'プレミアムプラン',
    monthlyPrice: 50000,
    setupFee: 80000,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'plan-003',
    orgId: ORG_ID,
    name: 'エンタープライズプラン',
    monthlyPrice: 100000,
    setupFee: 150000,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const agencies: Agency[] = [
  {
    id: 'agency-001',
    orgId: ORG_ID,
    agencyName: 'MEO代理店パートナー株式会社',
    email: 'partner@meo-agency.example.com',
    password: 'password123',
    postalCode: '150-0001',
    prefecture: '東京都',
    addressDetail: '渋谷区神宮前5-5-5 代理店ビル3F',
    phoneArea: '03',
    phoneLocal: '1111',
    phoneNumber: '2222',
    instagramWholesalePrice: 20000,
    googleManagementWholesalePrice: 15000,
    instagramGoogleSetWholesalePrice: 30000,
    manager: '山田太郎',
    instagramAlertEmails: 'alert@meo-agency.example.com',
    influencerAlertEmails: 'influencer@meo-agency.example.com',
    recruitAlertEmails: null,
    memo: '主要代理店。月間10件以上の獲得実績あり。',
    acquiredLocationCount: 45,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
]

export const accounts: Account[] = [
  {
    id: 'account-001',
    orgId: ORG_ID,
    accountName: '渋谷カフェ本店',
    adminEmail: 'admin@shibuya-cafe.example.com',
    password: 'cafe123',
    postalCode: '150-0043',
    prefecture: '東京都',
    addressDetail: '渋谷区道玄坂1-2-3 カフェビル1F',
    phoneArea: '03',
    phoneLocal: '1234',
    phoneNumber: '5678',
    accountManager: '佐藤花子',
    lineOfficialNotification: true,
    influencerDbPlan: 'free',
    memo: null,
    instagramIntegration: 'connected',
    gbpManagement: 'connected',
    instagramGbpIntegration: 'connected',
    totalContracts: 1,
    totalMonthlyFee: 30000,
    agencyId: 'agency-001',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'account-002',
    orgId: ORG_ID,
    accountName: '新宿ラーメン太郎',
    adminEmail: 'admin@ramen-taro.example.com',
    password: 'ramen456',
    postalCode: '160-0021',
    prefecture: '東京都',
    addressDetail: '新宿区歌舞伎町1-1-1 ラーメンビル2F',
    phoneArea: '03',
    phoneLocal: '2345',
    phoneNumber: '6789',
    accountManager: '鈴木一郎',
    lineOfficialNotification: true,
    influencerDbPlan: 'unlimited',
    memo: '大口顧客。丁寧に対応すること。',
    instagramIntegration: 'connected',
    gbpManagement: 'connected',
    instagramGbpIntegration: 'connected',
    totalContracts: 1,
    totalMonthlyFee: 50000,
    agencyId: null,
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'account-003',
    orgId: ORG_ID,
    accountName: '池袋美容室BLOOM',
    adminEmail: 'admin@bloom.example.com',
    password: 'bloom789',
    postalCode: '171-0022',
    prefecture: '東京都',
    addressDetail: '豊島区東池袋2-3-4 美容ビル5F',
    phoneArea: '03',
    phoneLocal: '3456',
    phoneNumber: '7890',
    accountManager: '田中美咲',
    lineOfficialNotification: false,
    influencerDbPlan: 'free',
    memo: null,
    instagramIntegration: 'connected',
    gbpManagement: 'error',
    instagramGbpIntegration: 'not_connected',
    totalContracts: 1,
    totalMonthlyFee: 30000,
    agencyId: 'agency-001',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'account-004',
    orgId: ORG_ID,
    accountName: '横浜中華料理龍門',
    adminEmail: 'admin@ryumon.example.com',
    password: 'ryumon321',
    postalCode: '231-0023',
    prefecture: '神奈川県',
    addressDetail: '横浜市中区山下町100 中華街ビル1F',
    phoneArea: '045',
    phoneLocal: '123',
    phoneNumber: '4567',
    accountManager: '高橋健太',
    lineOfficialNotification: true,
    influencerDbPlan: 'unlimited',
    memo: '来月から稼働開始予定',
    instagramIntegration: 'pending',
    gbpManagement: 'pending',
    instagramGbpIntegration: 'not_connected',
    totalContracts: 1,
    totalMonthlyFee: 100000,
    agencyId: null,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'account-005',
    orgId: ORG_ID,
    accountName: '大阪たこ焼きまんぷく',
    adminEmail: 'admin@manpuku.example.com',
    password: 'tako654',
    postalCode: '542-0071',
    prefecture: '大阪府',
    addressDetail: '大阪市中央区道頓堀1-5-5 たこ焼きビル1F',
    phoneArea: '06',
    phoneLocal: '1234',
    phoneNumber: '5678',
    accountManager: '伊藤次郎',
    lineOfficialNotification: false,
    influencerDbPlan: 'free',
    memo: '商談中',
    instagramIntegration: 'not_connected',
    gbpManagement: 'not_connected',
    instagramGbpIntegration: 'not_connected',
    totalContracts: 0,
    totalMonthlyFee: 0,
    agencyId: null,
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
]

export const linkageErrors: LinkageError[] = [
  {
    id: 'error-001',
    orgId: ORG_ID,
    accountId: 'account-003',
    accountName: '池袋美容室BLOOM',
    adminEmail: 'admin@bloom.example.com',
    locationId: 'loc-003',
    locationName: '池袋美容室BLOOM',
    facebookError: null,
    instagramError: null,
    gbpError: 'GBPアクセストークンの有効期限が切れています。再認証が必要です。',
    lineError: null,
    detectedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 3),
    resolvedAt: null,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 3),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 3),
  },
]

export const contracts: Contract[] = [
  {
    id: 'contract-001',
    orgId: ORG_ID,
    accountId: 'account-001',
    planId: 'plan-001',
    status: 'active',
    startDate: new Date('2024-07-01'),
    endDate: null,
    billingMethod: 'monthlypay',
    contractMonthlyPriceSnapshot: 30000,
    salesOwnerUserId: USER_ID,
    opsOwnerUserId: USER_ID,
    cancellationRequestedAt: null,
    cancellationEffectiveDate: null,
    cancellationReason: null,
    paymentDay: 10,
    notes: null,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'contract-002',
    orgId: ORG_ID,
    accountId: 'account-002',
    planId: 'plan-002',
    status: 'active',
    startDate: new Date('2024-08-01'),
    endDate: null,
    billingMethod: 'invoice',
    contractMonthlyPriceSnapshot: 50000,
    salesOwnerUserId: USER_ID,
    opsOwnerUserId: USER_ID,
    cancellationRequestedAt: null,
    cancellationEffectiveDate: null,
    cancellationReason: null,
    paymentDay: 25,
    notes: '大口顧客。丁寧に対応すること。',
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'contract-003',
    orgId: ORG_ID,
    accountId: 'account-003',
    planId: 'plan-001',
    status: 'cancel_pending',
    startDate: new Date('2024-09-01'),
    endDate: null,
    billingMethod: 'monthlypay',
    contractMonthlyPriceSnapshot: 30000,
    salesOwnerUserId: USER_ID,
    opsOwnerUserId: USER_ID,
    cancellationRequestedAt: new Date(now.getFullYear(), now.getMonth(), 5),
    cancellationEffectiveDate: nextMonth,
    cancellationReason: '事業縮小のため',
    paymentDay: 15,
    notes: null,
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date(now.getFullYear(), now.getMonth(), 5),
  },
  {
    id: 'contract-004',
    orgId: ORG_ID,
    accountId: 'account-004',
    planId: 'plan-003',
    status: 'closed_won',
    startDate: nextMonth,
    endDate: null,
    billingMethod: 'invoice',
    contractMonthlyPriceSnapshot: 100000,
    salesOwnerUserId: USER_ID,
    opsOwnerUserId: null,
    cancellationRequestedAt: null,
    cancellationEffectiveDate: null,
    cancellationReason: null,
    paymentDay: 20,
    notes: '来月から稼働開始予定',
    createdAt: new Date(now.getFullYear(), now.getMonth(), 10),
    updatedAt: new Date(now.getFullYear(), now.getMonth(), 10),
  },
  {
    id: 'contract-005',
    orgId: ORG_ID,
    accountId: 'account-005',
    planId: 'plan-001',
    status: 'lead',
    startDate: nextMonth,
    endDate: null,
    billingMethod: 'monthlypay',
    contractMonthlyPriceSnapshot: 30000,
    salesOwnerUserId: USER_ID,
    opsOwnerUserId: null,
    cancellationRequestedAt: null,
    cancellationEffectiveDate: null,
    cancellationReason: null,
    paymentDay: 10,
    notes: '商談中',
    createdAt: new Date(now.getFullYear(), now.getMonth(), 1),
    updatedAt: new Date(now.getFullYear(), now.getMonth(), 1),
  },
]

export const invoices: Invoice[] = [
  {
    id: 'invoice-001',
    orgId: ORG_ID,
    contractId: 'contract-001',
    billingMonth: lastMonth,
    amount: 30000,
    status: 'paid',
    dueDate: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
    pdfUrl: null,
    sentAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1),
    issueDate: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1),
    adjustmentNote: null,
    createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1),
    updatedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
  },
  {
    id: 'invoice-002',
    orgId: ORG_ID,
    contractId: 'contract-001',
    billingMonth: thisMonth,
    amount: 30000,
    status: 'paid',
    dueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
    pdfUrl: null,
    sentAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    issueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    adjustmentNote: null,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
  },
  {
    id: 'invoice-003',
    orgId: ORG_ID,
    contractId: 'contract-002',
    billingMonth: lastMonth,
    amount: 50000,
    status: 'paid',
    dueDate: new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 0),
    pdfUrl: '/invoices/invoice-003.pdf',
    sentAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 5),
    issueDate: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1),
    adjustmentNote: null,
    createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1),
    updatedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 28),
  },
  {
    id: 'invoice-004',
    orgId: ORG_ID,
    contractId: 'contract-002',
    billingMonth: thisMonth,
    amount: 50000,
    status: 'overdue',
    dueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
    pdfUrl: '/invoices/invoice-004.pdf',
    sentAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 5),
    issueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    adjustmentNote: null,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 16),
  },
  {
    id: 'invoice-005',
    orgId: ORG_ID,
    contractId: 'contract-003',
    billingMonth: thisMonth,
    amount: 30000,
    status: 'sent',
    dueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
    pdfUrl: null,
    sentAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    issueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    adjustmentNote: '最終請求',
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 1),
  },
  {
    id: 'invoice-006',
    orgId: ORG_ID,
    contractId: 'contract-004',
    billingMonth: nextMonth,
    amount: 100000,
    status: 'draft',
    dueDate: new Date(nextMonth.getFullYear(), nextMonth.getMonth(), 20),
    pdfUrl: null,
    sentAt: null,
    issueDate: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
    adjustmentNote: '初回請求（初期費用込）',
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
  },
]

export const payments: Payment[] = [
  {
    id: 'payment-001',
    orgId: ORG_ID,
    contractId: 'contract-001',
    invoiceId: 'invoice-001',
    provider: 'monthlypay',
    providerPaymentId: 'mp-001',
    amount: 30000,
    currency: 'JPY',
    status: 'succeeded',
    paidAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
    failureReason: null,
    createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
  },
  {
    id: 'payment-002',
    orgId: ORG_ID,
    contractId: 'contract-001',
    invoiceId: 'invoice-002',
    provider: 'monthlypay',
    providerPaymentId: 'mp-002',
    amount: 30000,
    currency: 'JPY',
    status: 'succeeded',
    paidAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
    failureReason: null,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
  },
  {
    id: 'payment-003',
    orgId: ORG_ID,
    contractId: 'contract-002',
    invoiceId: 'invoice-003',
    provider: 'bank_transfer',
    providerPaymentId: null,
    amount: 50000,
    currency: 'JPY',
    status: 'succeeded',
    paidAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 28),
    failureReason: null,
    createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 28),
  },
  {
    id: 'payment-004',
    orgId: ORG_ID,
    contractId: 'contract-003',
    invoiceId: 'invoice-005',
    provider: 'monthlypay',
    providerPaymentId: 'mp-003',
    amount: 30000,
    currency: 'JPY',
    status: 'failed',
    paidAt: null,
    failureReason: 'カード有効期限切れ',
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 15),
  },
]

export const routeIntegrations: RouteIntegration[] = [
  {
    id: 'route-001',
    orgId: ORG_ID,
    contractId: 'contract-001',
    accountId: 'account-001',
    routeCustomerId: 'rc-001',
    routeStoreId: 'rs-001',
    locationId: 'loc-001',
    locationName: '渋谷カフェ本店',
    status: 'running',
    runningStartedAt: new Date('2024-07-01'),
    stoppedAt: null,
    lastError: null,
    facebookStatus: 'connected',
    instagramStatus: 'connected',
    gbpStatus: 'connected',
    lineStatus: 'connected',
    facebookError: null,
    instagramError: null,
    gbpError: null,
    lineError: null,
    gbpGroupId: '5895311557',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'route-002',
    orgId: ORG_ID,
    contractId: 'contract-002',
    accountId: 'account-002',
    routeCustomerId: 'rc-002',
    routeStoreId: 'rs-002',
    locationId: 'loc-002',
    locationName: '新宿ラーメン太郎',
    status: 'running',
    runningStartedAt: new Date('2024-08-01'),
    stoppedAt: null,
    lastError: null,
    facebookStatus: 'connected',
    instagramStatus: 'connected',
    gbpStatus: 'connected',
    lineStatus: 'connected',
    facebookError: null,
    instagramError: null,
    gbpError: null,
    lineError: null,
    gbpGroupId: '5895311557',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'route-003',
    orgId: ORG_ID,
    contractId: 'contract-003',
    accountId: 'account-003',
    routeCustomerId: 'rc-003',
    routeStoreId: 'rs-003',
    locationId: 'loc-003',
    locationName: '池袋美容室BLOOM',
    status: 'paused',
    runningStartedAt: new Date('2024-09-01'),
    stoppedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 5),
    lastError: 'GBP連携エラーにより一時停止',
    facebookStatus: 'connected',
    instagramStatus: 'connected',
    gbpStatus: 'error',
    lineStatus: 'not_connected',
    facebookError: null,
    instagramError: null,
    gbpError: 'GBPアクセストークンの有効期限が切れています',
    lineError: null,
    gbpGroupId: '5895311557',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 5),
  },
  {
    id: 'route-004',
    orgId: ORG_ID,
    contractId: 'contract-004',
    accountId: 'account-004',
    routeCustomerId: null,
    routeStoreId: null,
    locationId: null,
    locationName: null,
    status: 'preparing',
    runningStartedAt: null,
    stoppedAt: null,
    lastError: null,
    facebookStatus: 'pending',
    instagramStatus: 'pending',
    gbpStatus: 'pending',
    lineStatus: 'not_connected',
    facebookError: null,
    instagramError: null,
    gbpError: null,
    lineError: null,
    gbpGroupId: null,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
    updatedAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 10),
  },
]

export const notifications: Notification[] = [
  {
    id: 'notification-001',
    orgId: ORG_ID,
    contractId: 'contract-002',
    invoiceId: 'invoice-004',
    paymentId: null,
    type: 'reminder_1',
    channel: 'email',
    toEmail: 'contact@ramen-taro.example.com',
    subject: '【ご案内】新宿ラーメン太郎様｜1月分 お支払いのご確認',
    body: '新宿ラーメン太郎様\n\nお支払い期限を過ぎております。ご確認をお願いいたします。',
    status: 'draft',
    errorMessage: null,
    sentAt: null,
    createdBy: USER_ID,
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 17),
  },
]

export const opsLogs: OpsLog[] = [
  {
    id: 'opslog-001',
    orgId: ORG_ID,
    contractId: 'contract-001',
    actorUserId: USER_ID,
    action: 'status_changed',
    before: { status: 'closed_won' },
    after: { status: 'active' },
    reason: '初回入金確認完了',
    createdAt: new Date('2024-07-01'),
  },
  {
    id: 'opslog-002',
    orgId: ORG_ID,
    contractId: 'contract-003',
    actorUserId: USER_ID,
    action: 'cancellation_requested',
    before: { status: 'active' },
    after: { status: 'cancel_pending' },
    reason: '事業縮小のため解約希望',
    createdAt: new Date(thisMonth.getFullYear(), thisMonth.getMonth(), 5),
  },
]

export const agents: Agent[] = [
  {
    id: 'agent-001',
    orgId: ORG_ID,
    name: 'MEOパートナー株式会社',
    contractStartDate: new Date('2024-04-01'),
    contractEndDate: null,
    stockUnitPrice: 20000,
    monthlyTarget: 10,
    settlementType: 'stock_only',
    isActive: true,
    contactEmail: 'contact@meo-partner.example.com',
    contactPhone: '03-9999-0001',
    bankName: 'みずほ銀行',
    bankBranch: '渋谷支店',
    bankAccountType: 'ordinary',
    bankAccountNumber: '1234567',
    bankAccountHolder: 'メオパートナー（カ',
    notes: '主要代理店。月10件目標。',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'agent-002',
    orgId: ORG_ID,
    name: '地域営業サポート合同会社',
    contractStartDate: new Date('2024-06-01'),
    contractEndDate: null,
    stockUnitPrice: 18000,
    monthlyTarget: 5,
    settlementType: 'stock_only',
    isActive: true,
    contactEmail: 'info@chiiki-support.example.com',
    contactPhone: '06-8888-0002',
    bankName: '三菱UFJ銀行',
    bankBranch: '梅田支店',
    bankAccountType: 'ordinary',
    bankAccountNumber: '7654321',
    bankAccountHolder: 'チイキエイギョウサポート（ド',
    notes: '関西エリア担当。',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'agent-003',
    orgId: ORG_ID,
    name: 'デジタルマーケティング社',
    contractStartDate: new Date('2024-01-01'),
    contractEndDate: new Date('2024-09-30'),
    stockUnitPrice: 22000,
    monthlyTarget: 8,
    settlementType: 'stock_only',
    isActive: false,
    contactEmail: 'sales@digimkt.example.com',
    contactPhone: '052-7777-0003',
    bankName: '名古屋銀行',
    bankBranch: '本店',
    bankAccountType: 'ordinary',
    bankAccountNumber: '9876543',
    bankAccountHolder: 'デジタルマーケティング（カ',
    notes: '契約終了済み。',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-09-30'),
  },
]

export const agentContracts: AgentContract[] = [
  {
    id: 'agent-contract-001',
    agentId: 'agent-001',
    contractId: 'contract-001',
    billingMonth: new Date('2024-07-01'),
    status: 'active',
    createdAt: new Date('2024-07-01'),
  },
  {
    id: 'agent-contract-002',
    agentId: 'agent-001',
    contractId: 'contract-002',
    billingMonth: new Date('2024-08-01'),
    status: 'active',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'agent-contract-003',
    agentId: 'agent-002',
    contractId: 'contract-003',
    billingMonth: new Date('2024-09-01'),
    status: 'cancelled',
    createdAt: new Date('2024-09-01'),
  },
]

export const agentPerformances: AgentMonthlyPerformance[] = [
  {
    id: 'perf-001',
    agentId: 'agent-001',
    billingMonth: lastMonth,
    acquiredCount: 3,
    createdAt: lastMonth,
  },
  {
    id: 'perf-002',
    agentId: 'agent-001',
    billingMonth: thisMonth,
    acquiredCount: 2,
    createdAt: thisMonth,
  },
  {
    id: 'perf-003',
    agentId: 'agent-002',
    billingMonth: lastMonth,
    acquiredCount: 1,
    createdAt: lastMonth,
  },
  {
    id: 'perf-004',
    agentId: 'agent-002',
    billingMonth: thisMonth,
    acquiredCount: 2,
    createdAt: thisMonth,
  },
]

export const agentEntitlements: AgentMonthlyEntitlement[] = [
  {
    id: 'entitle-001',
    agentId: 'agent-001',
    billingMonth: lastMonth,
    entitledCount: 10,
    earnedCount: 8,
    deficitCount: 2,
    createdAt: lastMonth,
  },
  {
    id: 'entitle-002',
    agentId: 'agent-001',
    billingMonth: thisMonth,
    entitledCount: 10,
    earnedCount: 9,
    deficitCount: 1,
    createdAt: thisMonth,
  },
  {
    id: 'entitle-003',
    agentId: 'agent-002',
    billingMonth: lastMonth,
    entitledCount: 5,
    earnedCount: 4,
    deficitCount: 1,
    createdAt: lastMonth,
  },
  {
    id: 'entitle-004',
    agentId: 'agent-002',
    billingMonth: thisMonth,
    entitledCount: 5,
    earnedCount: 5,
    deficitCount: 0,
    createdAt: thisMonth,
  },
]

export const agentSettlements: AgentSettlement[] = [
  {
    id: 'settlement-001',
    agentId: 'agent-001',
    billingMonth: lastMonth,
    entitledCount: 10,
    payableCount: 7,
    cancelledOffset: 1,
    unitPrice: 20000,
    totalAmount: 140000,
    status: 'paid',
    invoiceId: 'agent-inv-001',
    payoutMethod: 'manual',
    payoutStatus: 'paid',
    payoutRequestedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 25),
    payoutCompletedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 5),
    payoutProvider: null,
    payoutProviderId: null,
    payoutErrorReason: null,
    createdAt: lastMonth,
    updatedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 5),
  },
  {
    id: 'settlement-002',
    agentId: 'agent-001',
    billingMonth: thisMonth,
    entitledCount: 10,
    payableCount: 9,
    cancelledOffset: 0,
    unitPrice: 20000,
    totalAmount: 180000,
    status: 'invoiced',
    invoiceId: 'agent-inv-002',
    payoutMethod: null,
    payoutStatus: 'unpaid',
    payoutRequestedAt: null,
    payoutCompletedAt: null,
    payoutProvider: null,
    payoutProviderId: null,
    payoutErrorReason: null,
    createdAt: thisMonth,
    updatedAt: thisMonth,
  },
  {
    id: 'settlement-003',
    agentId: 'agent-002',
    billingMonth: lastMonth,
    entitledCount: 5,
    payableCount: 3,
    cancelledOffset: 1,
    unitPrice: 18000,
    totalAmount: 54000,
    status: 'paid',
    invoiceId: 'agent-inv-003',
    payoutMethod: 'manual',
    payoutStatus: 'paid',
    payoutRequestedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 25),
    payoutCompletedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 5),
    payoutProvider: null,
    payoutProviderId: null,
    payoutErrorReason: null,
    createdAt: lastMonth,
    updatedAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 5),
  },
  {
    id: 'settlement-004',
    agentId: 'agent-002',
    billingMonth: thisMonth,
    entitledCount: 5,
    payableCount: 5,
    cancelledOffset: 0,
    unitPrice: 18000,
    totalAmount: 90000,
    status: 'draft',
    invoiceId: null,
    payoutMethod: null,
    payoutStatus: 'unpaid',
    payoutRequestedAt: null,
    payoutCompletedAt: null,
    payoutProvider: null,
    payoutProviderId: null,
    payoutErrorReason: null,
    createdAt: thisMonth,
    updatedAt: thisMonth,
  },
]

export const DEFAULT_ORG_ID = ORG_ID
export const DEFAULT_USER_ID = USER_ID
